name:                PrototypeWithInterface
version:             0.1.0.0
github:              "Human-Oriented-ATP/PrototypeWithInterface"
license:             BSD3
author:              "Wills Wynn Thomas & Bhavik Mehta"
maintainer:          "willswynnthomas@gmail.com"
copyright:           "2022 Wills Wynn Thomas"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Prototype for an interactive motivated theorem prover with a webapp interface.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Human-Oriented-ATP/PrototypeWithInterface>

dependencies:
- base >= 4.7 && < 5
- scotty >= 0.12
- blaze-html >= 0.9
- blaze-markup
- text
- containers
- http-types
- unordered-containers
- mtl
- hashable
- parser-combinators
- megaparsec
- wai-extra
- wai-middleware-static
- aeson
- wai-cors
- bytestring
- wai
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  PrototypeWithInterface-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PrototypeWithInterface

tests:
  PrototypeWithInterface-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PrototypeWithInterface
